pool:
  vmImage: vs2017-win2016
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - Functions/*
steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: 'Functions/*.csproj'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'Functions/*.csproj'
    arguments: '--configuration Release'
- task: DotNetCoreCLI@2
  inputs:
    command: publish
    arguments: '--configuration Release --output publish_output'
    projects: '*.csproj'
    publishWebProjects: false
    modifyOutputPath: true
    zipAfterPublish: false
    workingDirectory: '$(System.DefaultWorkingDirectory)/Functions'
- task: ArchiveFiles@2
  displayName: "Archive files"
  inputs:
    rootFolderOrFile: "$(System.DefaultWorkingDirectory)/Functions/publish_output"
    includeRootFolder: false
    archiveFile: "$(System.DefaultWorkingDirectory)/functions_build$(Build.BuildId).zip"
- task: PublishPipelineArtifact@1
  inputs:
    artifact: 'functions-drop'
    path: '$(System.DefaultWorkingDirectory)/functions_build$(Build.BuildId).zip'