pool:
  vmImage: vs2017-win2016
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - templates/*
steps:
- task: AzureResourceGroupDeployment@2
  displayName: 'Validate ARM Template'
  inputs:
    azureSubscription: $(AZURE_SUBSCRIPTION)
    resourceGroupName: $(RESOURCE_GROUP_NAME)
    location: $(RG_LOCATION)
    templateLocation: Linked artifact
    csmFile: 'templates/azuredeploy.json'
    csmParametersFile: 'templates/azuredeploy.parameters.json'
    deploymentMode: Validation
  condition: always()
- task: AzureCLI@1
  displayName: 'Clean up RG'
  inputs:
    azureSubscription: $(AZURE_SUBSCRIPTION)
    scriptLocation: inlineScript
    inlineScript: 'az group delete -n $(RESOURCE_GROUP_NAME) --yes'
- task: ArchiveFiles@2
  displayName: "Archive files"
  inputs:
    rootFolderOrFile: "$(System.DefaultWorkingDirectory)/templates"
    includeRootFolder: false
    archiveFile: "$(System.DefaultWorkingDirectory)/templates/build$(Build.BuildId).zip"
- task: PublishPipelineArtifact@1
  inputs:
    artifact: 'templates-drop'
    path: '$(System.DefaultWorkingDirectory)/templates/build$(Build.BuildId).zip'